# Generated by Django 4.1.4 on 2022-12-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_entete_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='produit_BL',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.produit'),
            preserve_default=False,
        ),
    ]
