# Generated by Django 4.1.4 on 2022-12-30 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_facture_produit_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='quantite',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Le champ doit être positif')]),
        ),
    ]
