# Generated by Django 4.1.4 on 2022-12-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_facture_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
